include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    always_use_package_imports: true
    unawaited_futures: true

# riverpod_lint configurations (optional tweaks)
riverpod_lint:
  rules:
    - avoid_public_notifier_properties: true
    - prefer_final_provider_parameters: true
    - provider_dependencies: true
