name: meet_sam_ava
description: MVVM starter using Flutter + Riverpod 3 + AutoRoute + Formz, with riverpod_lint + custom_lint.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # Riverpod 3
  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17

  # Routing
  auto_route: ^10.1.2

  # Forms & validation
  formz: ^0.8.0
  dartz: ^0.10.1

  # Charts
  fl_chart: ^0.69.0
  intl: ^0.20.2

  # Visibility detection for scroll-based animations
  visibility_detector: ^0.4.0+2

  # Persistent storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Codegen
  build_runner: ^2.4.11
  riverpod_generator: ^3.0.0-dev.17
  auto_route_generator: ^10.2.4

  riverpod_lint: ^3.0.0-dev.17
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/icons/sam_app_icon_512.png"
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/sam_app_icon_512.png"
    background_color: "#FFF2F0ED"

flutter:
  uses-material-design: true

  fonts:
    - family: At Hauss
      fonts:
        - asset: assets/fonts/AtHauss-Regular.ttf
          weight: 400
        - asset: assets/fonts/AtHauss-Medium.ttf
          weight: 500
        - asset: assets/fonts/AtHauss-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AtHauss-Bold.ttf
          weight: 700

    - family: At Slam Cnd
      fonts:
        - asset: assets/fonts/AtSlamCnd-Regular.ttf
          weight: 400
        - asset: assets/fonts/AtSlamCnd-Medium.ttf
          weight: 500
        - asset: assets/fonts/AtSlamCnd-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AtSlamCnd-Bold.ttf
          weight: 700
